# Generated by Django 4.2.6 on 2024-08-06 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('portal', models.CharField(max_length=50)),
                ('judul', models.CharField(max_length=255)),
                ('konten', models.TextField()),
                ('jumlah_komentar', models.PositiveIntegerField()),
                ('timestamp_scrape', models.DateTimeField(verbose_name='Timestamp Scrape')),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penulis_komentar', models.CharField(max_length=255)),
                ('isi_komentar', models.TextField()),
                ('prediksi', models.CharField(blank=True, max_length=10, null=True)),
                ('probabilitas', models.FloatField(blank=True, null=True)),
                ('berita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar_set', to='hateapp.berita')),
            ],
        ),
    ]
