# Generated by Django 4.2.6 on 2024-01-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('konten', models.TextField()),
                ('link', models.URLField()),
                ('jumlah_komentar', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penulis_komentar', models.CharField(max_length=255)),
                ('isi_komentar', models.TextField()),
                ('berita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hateapp.berita')),
            ],
        ),
    ]
