# Generated by Django 4.2.6 on 2024-08-09 08:44

from django.db import migrations, models
import hateapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('hateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='id',
            field=models.CharField(default=hateapp.models.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='id',
            field=models.CharField(default=hateapp.models.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
