# Generated by Django 4.2.6 on 2024-01-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateapp', '0003_alter_berita_jumlah_komentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='prediksi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
