# Generated by Django 4.2.6 on 2024-01-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateapp', '0004_komentar_prediksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='timestamp_scrape',
            field=models.DateTimeField(auto_now=True, verbose_name='Timestamp Scrape'),
        ),
    ]
