# Generated by Django 4.2.6 on 2024-01-10 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hateapp', '0008_editrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditRequest',
        ),
    ]
