# Generated by Django 4.2.6 on 2024-01-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateapp', '0011_editprediksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='editprediksi',
            name='alasan_penolakan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editprediksi',
            name='disetujui',
            field=models.BooleanField(default=False),
        ),
    ]
