# Generated by Django 4.2.6 on 2024-01-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hateapp', '0012_editprediksi_alasan_penolakan_editprediksi_disetujui'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editprediksi',
            name='alasan_penolakan',
        ),
        migrations.RemoveField(
            model_name='editprediksi',
            name='disetujui',
        ),
    ]
