# Generated by Django 4.2.6 on 2024-01-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateapp', '0015_editprediksi_sudahditinjau'),
    ]

    operations = [
        migrations.AddField(
            model_name='editprediksi',
            name='statusadmin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
