# Generated by Django 4.2.6 on 2024-01-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='portal',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
