# Generated by Django 4.2.6 on 2024-01-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateapp', '0002_berita_portal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='jumlah_komentar',
            field=models.PositiveIntegerField(),
        ),
    ]
