# Generated by Django 4.2.6 on 2024-01-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateapp', '0005_berita_timestamp_scrape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='timestamp_scrape',
            field=models.DateTimeField(verbose_name='Timestamp Scrape'),
        ),
    ]
