# Generated by Django 4.2.6 on 2024-01-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateapp', '0006_alter_berita_timestamp_scrape'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='probabilitas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
