# Generated by Django 4.2.6 on 2024-01-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hateapp', '0007_komentar_probabilitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('prediksi_seharusnya', models.CharField(max_length=10)),
                ('alasan', models.TextField()),
                ('disetujui', models.BooleanField(default=False)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('komentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hateapp.komentar')),
            ],
        ),
    ]
