# Generated by Django 4.2.6 on 2024-01-18 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hateapp', '0009_delete_editrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='berita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar_set', to='hateapp.berita'),
        ),
    ]
