# Generated by Django 4.2.6 on 2024-01-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateapp', '0013_remove_editprediksi_alasan_penolakan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editprediksi',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
