# Generated by Django 4.2.6 on 2024-01-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateapp', '0014_editprediksi_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='editprediksi',
            name='sudahditinjau',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
